FROM node:18

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh /usr/local/bin/wait-for-it
RUN chmod +x /usr/local/bin/wait-for-it

# Exposer le port 3000
EXPOSE 3000
