services:
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    command: npm run start:dev
    profiles:
      - dev

  backend-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3000:3000'
    command: npm run start:prod
    profiles:
      - prod
